As of this commit the Anomaly model fails with IoTimeoutError
As of this commit the Anomaly model fails with:

INFO:tvm.micro.contrib.zephyr:Memory region         Used Size  Region Size  %age Used
INFO:tvm.micro.contrib.zephyr:--------------------- ---------- ------------ ---------
INFO:tvm.micro.contrib.zephyr:           FLASH:       44628 B         1 MB      4.26%
INFO:tvm.micro.contrib.zephyr:            DTCM:          0 GB        64 KB      0.00%
INFO:tvm.micro.contrib.zephyr:            SRAM:      235776 B       256 KB     89.94%
INFO:tvm.micro.contrib.zephyr:        IDT_LIST:          0 GB         2 KB      0.00%
INFO:tvm.micro.contrib.zephyr:Logical command for additional byproducts on target: zephyr_final
DEBUG:tvm.micro.contrib.zephyr:zephyr openocd driver: autodetected serial 066CFF485153826687133653
Open On-Chip Debugger 0.10.0+dev-01341-g580d06d9d-dirty (2020-06-25-12:07)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
066CFF485153826687133653
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
Info : clock speed 2000 kHz
Info : STLINK V2J25M14 (API v2) VID:PID 0483:374B
Info : Target voltage: 3.238421
Warn : Silicon bug: single stepping may enter pending exception handler!
Info : stm32f7x.cpu: hardware has 8 breakpoints, 4 watchpoints
Info : Listening on port 3333 for gdb connections
    TargetName         Type       Endian TapName            State
--  ------------------ ---------- ------ ------------------ ------------
 0* stm32f7x.cpu       hla_target little stm32f7x.cpu       running

target halted due to debug-request, current mode: Thread
xPSR: 0x01000000 pc: 0x08002ad0 msp: 0x20048e80
Info : device id = 0x10016449
Info : flash size = 1024 kbytes
auto erase enabled
wrote 65536 bytes from file /tmp/tvm-debug-mode-tempdirs/2021-05-17T13-43-18___lvs4zrid/00000/build/runtime/zephyr/zephyr.hex in 1.512081s (42.326 KiB/s)

target halted due to debug-request, current mode: Thread
xPSR: 0x01000000 pc: 0x08002ad0 msp: 0x20048e80
verified 44628 bytes in 0.204515s (213.099 KiB/s)

shutdown command invoked
DEBUG:tvm.micro.contrib.zephyr:zephyr transport: found UART baudrate from devicetree: 115200
DEBUG:tvm.micro.transport.base:micro-rpc: opening transport
DEBUG:tvm.micro.transport.base:micro-rpc: write {10.00s}        <- [  1 B]: fe                                               .
DEBUG:tvm.micro.transport.base:micro-rpc: write {10.00s}        <- [  2 B]: ff fd                                            ..
DEBUG:tvm.micro.transport.base:micro-rpc: write {10.00s}        <- [  4 B]: 03 00 00 00                                      ....
DEBUG:tvm.micro.transport.base:micro-rpc: write {10.00s}        <- [  3 B]: 00 00 02                                         ...
DEBUG:tvm.micro.transport.base:micro-rpc: write {10.00s}        <- [  2 B]: 66 77                                            fw
DEBUG:tvm.micro.transport.base:micro-rpc: write {10.00s}        <- [  2 B]: ff fd                                            ..
DEBUG:tvm.micro.transport.base:micro-rpc: write {10.00s}        <- [  4 B]: 04 00 00 00                                      ....
DEBUG:tvm.micro.transport.base:micro-rpc: write {10.00s}        <- [  3 B]: 22 00 00                                         "..
DEBUG:tvm.micro.transport.base:micro-rpc: write {10.00s}        <- [  1 B]: 01                                               .
DEBUG:tvm.micro.transport.base:micro-rpc: write {10.00s}        <- [  2 B]: 0d 03                                            ..
DEBUG:tvm.micro.transport.base:micro-rpc: read { 5.00s}  128 B -> [ 26 B]:
0000  fe ff fd 03 00 00 00 00 00 02 66 77 ff fd 24 00  ..........fw..$.
0010  00 00 00 00 03 6d 69 63 72 6f                    .....micro
DEBUG:tvm.micro.transport.base:micro-rpc: read { 4.96s}  128 B -> [ 30 B]:
0000  54 56 4d 20 5a 65 70 68 79 72 20 72 75 6e 74 69  TVM.Zephyr.runti
0010  6d 65 20 2d 20 72 75 6e 6e 69 6e 67 26 4c        me.-.running&L
[13:43:50] /home/gromero/git/tvm_u_main/src/runtime/micro/micro_session.cc:364: remote: microTVM Zephyr runtime - running
DEBUG:tvm.micro.transport.base:micro-rpc: read { 4.96s}  128 B -> [IoTimeoutError  4.96s]
DEBUG:tvm.micro.transport.base:micro-rpc: write {10.00s}        <- [  2 B]: ff fd                                            ..
DEBUG:tvm.micro.transport.base:micro-rpc: write {10.00s}        <- [  4 B]: 03 00 00 00                                      ....
DEBUG:tvm.micro.transport.base:micro-rpc: write {10.00s}        <- [  3 B]: 00 00 02                                         ...
DEBUG:tvm.micro.transport.base:micro-rpc: write {10.00s}        <- [  2 B]: 66 77                                            fw
DEBUG:tvm.micro.transport.base:micro-rpc: write {10.00s}        <- [  2 B]: ff fd                                            ..
DEBUG:tvm.micro.transport.base:micro-rpc: write {10.00s}        <- [  4 B]: 04 00 00 00                                      ....
DEBUG:tvm.micro.transport.base:micro-rpc: write {10.00s}        <- [  3 B]: a2 00 00                                         ...
DEBUG:tvm.micro.transport.base:micro-rpc: write {10.00s}        <- [  1 B]: 01                                               .
DEBUG:tvm.micro.transport.base:micro-rpc: write {10.00s}        <- [  2 B]: 35 de                                            5.
DEBUG:tvm.micro.transport.base:micro-rpc: read { 5.00s}  128 B -> [  3 B]: ff fd 04                                         ...
DEBUG:tvm.micro.transport.base:micro-rpc: read { 5.00s}  128 B -> [  9 B]: 00 00 00 a2 43 01 01 f9 a9                       ....C....
DEBUG:tvm.micro.transport.base:micro-rpc: write {30.00s}        <- [  2 B]: ff fd                                            ..
DEBUG:tvm.micro.transport.base:micro-rpc: write {30.00s}        <- [  4 B]: 30 00 00 00                                      0...
DEBUG:tvm.micro.transport.base:micro-rpc: write {30.00s}        <- [  3 B]: a2 43 10                                         .C.
DEBUG:tvm.micro.transport.base:micro-rpc: write {30.00s}        <- [ 45 B]:
0000  25 00 00 00 00 00 00 00 09 00 00 00 01 00 00 00  %...............
0010  0b 00 00 00 11 00 00 00 00 00 00 00 72 75 6e 74  ............runt
0020  69 6d 65 2e 53 79 73 74 65 6d 4c 69 62           ime.SystemLib
DEBUG:tvm.micro.transport.base:micro-rpc: write {30.00s}        <- [  2 B]: dd 51                                            .Q
DEBUG:tvm.micro.transport.base:micro-rpc: read {30.00s}  128 B -> [  7 B]: ff fd 1f 00 00 00 a2                             .......
DEBUG:tvm.micro.transport.base:micro-rpc: read {30.00s}  128 B -> [ 36 B]:
0000  43 10 14 00 00 00 00 00 00 00 04 00 00 00 01 00  C...............
0010  00 00 03 00 00 00 00 80 02 80 ff ff ff ff ff ff  ................
0020  ff ff 64 6d                                      ..dm
DEBUG:tvm.micro.transport.base:micro-rpc: write {30.00s}        <- [  2 B]: ff fd                                            ..
DEBUG:tvm.micro.transport.base:micro-rpc: write {30.00s}        <- [  4 B]: 1b 00 00 00                                      ....
DEBUG:tvm.micro.transport.base:micro-rpc: write {30.00s}        <- [  3 B]: a2 43 10                                         .C.
DEBUG:tvm.micro.transport.base:micro-rpc: write {30.00s}        <- [ 28 B]:
0000  10 00 00 00 00 00 00 00 03 00 00 00 00 80 02 80  ................
0010  ff ff ff ff ff ff ff ff 00 00 00 00              ............
DEBUG:tvm.micro.transport.base:micro-rpc: write {30.00s}        <- [  3 B]: 05 ff ff                                         ...
DEBUG:tvm.micro.transport.base:micro-rpc: read {30.00s}  128 B -> [ 23 B]:
0000  ff fd 2b 00 00 00 a2 43 10 20 00 00 00 00 00 00  ..+....C........
0010  00 04 00 00 00 02 00                             .......
DEBUG:tvm.micro.transport.base:micro-rpc: read {30.00s}  128 B -> [ 28 B]:
0000  00 00 00 00 00 00 03 00 00 00 09 00 00 00 00 00  ................
0010  00 00 00 80 00 00 00 00 00 00 68 54              ..........hT
DEBUG:tvm.micro.transport.base:micro-rpc: write {30.00s}        <- [  2 B]: ff fd                                            ..
DEBUG:tvm.micro.transport.base:micro-rpc: write {30.00s}        <- [  4 B]: 2b 00 00 00                                      +...
DEBUG:tvm.micro.transport.base:micro-rpc: write {30.00s}        <- [  3 B]: a2 43 10                                         .C.
DEBUG:tvm.micro.transport.base:micro-rpc: write {30.00s}        <- [ 44 B]:
0000  20 00 00 00 00 00 00 00 0a 00 00 00 02 00 00 00  ................
0010  03 00 00 00 00 00 00 00 00 80 02 80 ff ff ff ff  ................
0020  ff ff ff ff 0a 00 00 00 00 00 00 00              ............
DEBUG:tvm.micro.transport.base:micro-rpc: write {30.00s}        <- [  2 B]: e8 b0                                            ..
DEBUG:tvm.micro.transport.base:micro-rpc: read {30.00s}  128 B -> [  8 B]: ff fd 17 00 00 00 a2 43                          .......C
DEBUG:tvm.micro.transport.base:micro-rpc: read {30.00s}  128 B -> [ 23 B]:
0000  10 0c 00 00 00 00 00 00 00 04 00 00 00 01 00 00  ................
0010  00 04 00 00 00 4c 5a                             .....LZ
DEBUG:tvm.micro.transport.base:micro-rpc: write {30.00s}        <- [  2 B]: ff fd                                            ..
DEBUG:tvm.micro.transport.base:micro-rpc: write {30.00s}        <- [  4 B]: 2b 00 00 00                                      +...
DEBUG:tvm.micro.transport.base:micro-rpc: write {30.00s}        <- [  3 B]: a2 43 10                                         .C.
DEBUG:tvm.micro.transport.base:micro-rpc: write {30.00s}        <- [ 40 B]:
0000  20 00 00 00 00 00 00 00 0a 00 00 00 02 00 00 00  ................
0010  03 00 00 00 00 00 00 00 00 80 00 00 00 00 00 00  ................
0020  09 00 00 00 00 00 00 00                          ........
DEBUG:tvm.micro.transport.base:micro-rpc: write {30.00s}        <- [  2 B]: 3c 61                                            <a
DEBUG:tvm.micro.transport.base:micro-rpc: read {30.00s}  128 B -> [ 13 B]: ff fd 17 00 00 00 a2 43 10 0c 00 00 00           .......C.....
DEBUG:tvm.micro.transport.base:micro-rpc: read {30.00s}  128 B -> [ 18 B]:
0000  00 00 00 00 04 00 00 00 01 00 00 00 04 00 00 00  ................
0010  4c 5a                                            LZ
DEBUG:tvm.micro.transport.base:micro-rpc: closing transport
Traceback (most recent call last):
  File "./utvm-anomaly-stm32.py", line 92, in <module>
    graph, session.get_system_lib(), session.context
AttributeError: 'Session' object has no attribute 'context'

The no attribute error is a red herring tho, because the root cause is
actually a timeout, so the most important error here is:

[13:43:50] /home/gromero/git/tvm_u_main/src/runtime/micro/micro_session.cc:364: remote: microTVM Zephyr runtime - running
DEBUG:tvm.micro.transport.base:micro-rpc: read { 4.96s}  128 B -> [IoTimeoutError  4.96s]

which happens quite early in the model transport to the MCU.

Futher investigation showed that at some point the micro target can't
allocate any more memory so it fails at this point (this is GDB
attached to the micro target whilst the model is request by the host
to run on the micro target):

Breakpoint 4, TVMPlatformMemoryAllocate (num_bytes=163840, ctx=..., out_ptr=out_ptr@entry=0x20033010 <z_main_stack+576>)
    at /home/gromero/git/tvm/tests/micro/qemu/zephyr-runtime/src/main.c:74
74	  *out_ptr = k_mem_pool_malloc(&tvm_memory_pool, num_bytes);
(gdb) n
75	  return (*out_ptr == NULL) ? kTvmErrorPlatformNoMemory : kTvmErrorNoError;
(gdb) p *out_ptr
$7 = (void *) 0x0
(gdb)

Signed-off-by: Gustavo Romero <gustavo.romero@linaro.org>