Enable FuseOps pass
Enable FuseOps pass which seems quite fundamental on TVM to generate the
correct final nodes for models in general, otherwise specifically for
the Anomaly model the compilation will fail with the following error,
where 'cast' is the name node/operator that must be fused:

TVMError: found cast; operators should be removed by future passes; try fusing and lowering

Signed-off-by: Gustavo Romero <gustavo.romero@linaro.org>